import { describe, expect, it } from "bun:test";
import {
  CountyScoreSchema,
  CountyScoresResponseSchema,
  CountyScoresStatusResponseSchema,
} from "@/index";

describe("county score contracts", () => {
  it("accepts a valid county market-pressure row", () => {
    const parsed = CountyScoreSchema.safeParse({
      countyFips: "06085",
      countyName: "Santa Clara",
      stateAbbrev: "CA",
      rankStatus: "deferred",
      attractivenessTier: "deferred",
      confidenceBadge: "low",
      marketPressureIndex: null,
      demandPressureScore: 76.1,
      supplyTimelineScore: null,
      gridFrictionScore: null,
      policyConstraintScore: null,
      freshnessScore: 92,
      lastUpdatedAt: "2026-03-07T00:00:00.000Z",
      sourceVolatility: "high",
      narrativeSummary: "Demand pressure is visible, but queue and policy baselines are missing.",
      topDrivers: [
        {
          code: "DEMAND_PIPELINE",
          impact: "headwind",
          label: "Demand pipeline",
          summary: "Stage-weighted near-term load additions remain elevated.",
        },
      ],
      deferredReasonCodes: ["MISSING_QUEUE_BASELINE", "MISSING_POLICY_BASELINE"],
      whatChanged30d: [],
      whatChanged60d: [],
      whatChanged90d: [],
      pillarValueStates: {
        demand: "observed",
        gridFriction: "unknown",
        infrastructure: "derived",
        policy: "unknown",
        supplyTimeline: "unknown",
      },
      expectedMw0To24m: 180,
      expectedMw24To60m: 70,
      recentCommissionedMw24m: 45,
      demandMomentumQoq: 0.32,
      providerEntryCount12m: 1,
      expectedSupplyMw0To36m: null,
      expectedSupplyMw36To60m: null,
      signedIaMw: null,
      queueMwActive: null,
      queueProjectCountActive: null,
      medianDaysInQueueActive: null,
      pastDueShare: null,
      marketWithdrawalPrior: null,
      congestionProxyScore: null,
      plannedUpgradeCount: null,
      heatmapSignalFlag: null,
      policyMomentumScore: null,
      moratoriumStatus: "unknown",
      publicSentimentScore: null,
      policyEventCount: null,
      countyTaggedEventShare: null,
      policyMappingConfidence: null,
      transmissionMiles69kvPlus: null,
      transmissionMiles230kvPlus: null,
      gasPipelinePresenceFlag: null,
      gasPipelineMileageCounty: null,
      fiberPresenceFlag: null,
      waterStressScore: 3.5,
      primaryMarketId: "silicon-valley",
      isSeamCounty: false,
      formulaVersion: "county-market-pressure-v1",
      inputDataVersion: "dc_pipeline=2026-03-07;water=mirror.water_stress_basins",
    });

    expect(parsed.success).toBe(true);
  });

  it("rejects invalid county fips values", () => {
    const parsed = CountyScoreSchema.safeParse({
      countyFips: "6085",
      countyName: "Santa Clara",
      stateAbbrev: "CA",
      rankStatus: "ranked",
      attractivenessTier: "advantaged",
      confidenceBadge: "high",
      marketPressureIndex: 22,
      demandPressureScore: 18,
      supplyTimelineScore: 24,
      gridFrictionScore: 16,
      policyConstraintScore: 20,
      freshnessScore: 88,
      lastUpdatedAt: "2026-03-07T00:00:00.000Z",
      sourceVolatility: "low",
      narrativeSummary: null,
      topDrivers: [],
      deferredReasonCodes: [],
      whatChanged30d: [],
      whatChanged60d: [],
      whatChanged90d: [],
      pillarValueStates: {
        demand: "observed",
        gridFriction: "observed",
        infrastructure: "derived",
        policy: "observed",
        supplyTimeline: "observed",
      },
      expectedMw0To24m: 0,
      expectedMw24To60m: 0,
      recentCommissionedMw24m: 0,
      demandMomentumQoq: 0,
      providerEntryCount12m: 0,
      expectedSupplyMw0To36m: 90,
      expectedSupplyMw36To60m: 60,
      signedIaMw: 30,
      queueMwActive: 120,
      queueProjectCountActive: 3,
      medianDaysInQueueActive: 420,
      pastDueShare: 0.2,
      marketWithdrawalPrior: 0.18,
      congestionProxyScore: 35,
      plannedUpgradeCount: 2,
      heatmapSignalFlag: true,
      policyMomentumScore: 12,
      moratoriumStatus: "none",
      publicSentimentScore: 45,
      policyEventCount: 2,
      countyTaggedEventShare: 1,
      policyMappingConfidence: "high",
      transmissionMiles69kvPlus: null,
      transmissionMiles230kvPlus: null,
      gasPipelinePresenceFlag: null,
      gasPipelineMileageCounty: null,
      fiberPresenceFlag: null,
      waterStressScore: 1.2,
      primaryMarketId: null,
      isSeamCounty: false,
      formulaVersion: "county-market-pressure-v1",
      inputDataVersion: "inputs-v1",
    });

    expect(parsed.success).toBe(false);
  });

  it("accepts county score responses with deferred and blocked county summaries", () => {
    const parsed = CountyScoresResponseSchema.safeParse({
      rows: [
        {
          countyFips: "06085",
          countyName: "Santa Clara",
          stateAbbrev: "CA",
          rankStatus: "deferred",
          attractivenessTier: "deferred",
          confidenceBadge: "low",
          marketPressureIndex: null,
          demandPressureScore: 76.1,
          supplyTimelineScore: null,
          gridFrictionScore: null,
          policyConstraintScore: null,
          freshnessScore: 92,
          lastUpdatedAt: "2026-03-07T00:00:00.000Z",
          sourceVolatility: "high",
          narrativeSummary: null,
          topDrivers: [],
          deferredReasonCodes: ["MISSING_QUEUE_BASELINE"],
          whatChanged30d: [],
          whatChanged60d: [],
          whatChanged90d: [],
          pillarValueStates: {
            demand: "observed",
            gridFriction: "unknown",
            infrastructure: "derived",
            policy: "unknown",
            supplyTimeline: "unknown",
          },
          expectedMw0To24m: 180,
          expectedMw24To60m: 70,
          recentCommissionedMw24m: 45,
          demandMomentumQoq: 0.32,
          providerEntryCount12m: 1,
          expectedSupplyMw0To36m: null,
          expectedSupplyMw36To60m: null,
          signedIaMw: null,
          queueMwActive: null,
          queueProjectCountActive: null,
          medianDaysInQueueActive: null,
          pastDueShare: null,
          marketWithdrawalPrior: null,
          congestionProxyScore: null,
          plannedUpgradeCount: null,
          heatmapSignalFlag: null,
          policyMomentumScore: null,
          moratoriumStatus: "unknown",
          publicSentimentScore: null,
          policyEventCount: null,
          countyTaggedEventShare: null,
          policyMappingConfidence: null,
          transmissionMiles69kvPlus: null,
          transmissionMiles230kvPlus: null,
          gasPipelinePresenceFlag: null,
          gasPipelineMileageCounty: null,
          fiberPresenceFlag: null,
          waterStressScore: 3.5,
          primaryMarketId: "silicon-valley",
          isSeamCounty: false,
          formulaVersion: "county-market-pressure-v1",
          inputDataVersion: "inputs-v1",
        },
      ],
      summary: {
        requestedCountyIds: ["06085", "48113"],
        missingCountyIds: ["48113"],
        deferredCountyIds: ["06085"],
        blockedCountyIds: [],
      },
      meta: {
        requestId: "req-123",
        sourceMode: "postgis",
        dataVersion: "dev",
        generatedAt: "2026-03-07T00:00:00.000Z",
        recordCount: 1,
        truncated: false,
        warnings: [],
      },
    });

    expect(parsed.success).toBe(true);
  });

  it("accepts county market-pressure dataset status responses", () => {
    const parsed = CountyScoresStatusResponseSchema.safeParse({
      datasetAvailable: true,
      publicationRunId: "county-market-pressure-20260307T000000Z",
      publishedAt: "2026-03-07T00:00:00.000Z",
      methodologyId: "county-market-pressure-v1",
      dataVersion: "2026-03-07",
      inputDataVersion: "dc_pipeline=2026-03-07;water=mirror.water_stress_basins",
      formulaVersion: "county-market-pressure-v1",
      rowCount: 3221,
      sourceCountyCount: 3221,
      rankedCountyCount: 0,
      deferredCountyCount: 3221,
      blockedCountyCount: 0,
      highConfidenceCount: 0,
      mediumConfidenceCount: 0,
      lowConfidenceCount: 3221,
      freshCountyCount: 3221,
      availableFeatureFamilies: ["demand", "history", "market_seams", "narratives", "water"],
      missingFeatureFamilies: ["grid_friction", "policy", "supply_timeline"],
      featureCoverage: {
        demand: true,
        gridFriction: false,
        history: true,
        infrastructure: true,
        marketSeams: true,
        narratives: true,
        policy: false,
        supplyTimeline: false,
      },
      meta: {
        requestId: "req-123",
        sourceMode: "postgis",
        dataVersion: "2026-03-07",
        generatedAt: "2026-03-07T00:00:00.000Z",
        recordCount: 1,
        truncated: false,
        warnings: [],
      },
    });

    expect(parsed.success).toBe(true);
  });
});
