export interface CountyScoreRow {
  readonly attractiveness_tier: string | null | undefined;
  readonly confidence_badge: string | null | undefined;
  readonly congestion_proxy_score: number | string | null | undefined;
  readonly county_fips: string;
  readonly county_name: string | null | undefined;
  readonly county_tagged_event_share: number | string | null | undefined;
  readonly deferred_reason_codes_json: unknown;
  readonly demand_momentum_qoq: number | string | null | undefined;
  readonly demand_pressure_score: number | string | null | undefined;
  readonly expected_mw_0_24m: number | string | null | undefined;
  readonly expected_mw_24_60m: number | string | null | undefined;
  readonly expected_supply_mw_0_36m: number | string | null | undefined;
  readonly expected_supply_mw_36_60m: number | string | null | undefined;
  readonly fiber_presence_flag: boolean | number | string | null | undefined;
  readonly formula_version: number | string | null | undefined;
  readonly freshness_score: number | string | null | undefined;
  readonly gas_pipeline_mileage_county: number | string | null | undefined;
  readonly gas_pipeline_presence_flag: boolean | number | string | null | undefined;
  readonly grid_friction_score: number | string | null | undefined;
  readonly has_county_reference: boolean | number | string | null | undefined;
  readonly has_county_score: boolean | number | string | null | undefined;
  readonly heatmap_signal_flag: boolean | number | string | null | undefined;
  readonly input_data_version: number | string | null | undefined;
  readonly is_seam_county: boolean | number | string | null | undefined;
  readonly last_updated_at: Date | string | null | undefined;
  readonly market_pressure_index: number | string | null | undefined;
  readonly market_withdrawal_prior: number | string | null | undefined;
  readonly median_days_in_queue_active: number | string | null | undefined;
  readonly moratorium_status: string | null | undefined;
  readonly narrative_summary: string | null | undefined;
  readonly past_due_share: number | string | null | undefined;
  readonly pillar_value_states_json: unknown;
  readonly planned_upgrade_count: number | string | null | undefined;
  readonly policy_constraint_score: number | string | null | undefined;
  readonly policy_event_count: number | string | null | undefined;
  readonly policy_mapping_confidence: string | null | undefined;
  readonly policy_momentum_score: number | string | null | undefined;
  readonly primary_market_id: string | null | undefined;
  readonly provider_entry_count_12m: number | string | null | undefined;
  readonly public_sentiment_score: number | string | null | undefined;
  readonly publication_run_id: string | null | undefined;
  readonly queue_mw_active: number | string | null | undefined;
  readonly queue_project_count_active: number | string | null | undefined;
  readonly rank_status: string | null | undefined;
  readonly recent_commissioned_mw_24m: number | string | null | undefined;
  readonly signed_ia_mw: number | string | null | undefined;
  readonly source_volatility: string | null | undefined;
  readonly state_abbrev: string | null | undefined;
  readonly supply_timeline_score: number | string | null | undefined;
  readonly top_drivers_json: unknown;
  readonly transmission_miles_69kv_plus: number | string | null | undefined;
  readonly transmission_miles_230kv_plus: number | string | null | undefined;
  readonly what_changed_30d_json: unknown;
  readonly what_changed_60d_json: unknown;
  readonly what_changed_90d_json: unknown;
}

export interface CountyScoresStatusRow {
  readonly available_feature_families: unknown;
  readonly blocked_county_count: number | string | null | undefined;
  readonly data_version: string | null | undefined;
  readonly deferred_county_count: number | string | null | undefined;
  readonly formula_version: string | null | undefined;
  readonly fresh_county_count: number | string | null | undefined;
  readonly high_confidence_count: number | string | null | undefined;
  readonly input_data_version: string | null | undefined;
  readonly low_confidence_count: number | string | null | undefined;
  readonly medium_confidence_count: number | string | null | undefined;
  readonly methodology_id: string | null | undefined;
  readonly missing_feature_families: unknown;
  readonly publication_run_id: string | null | undefined;
  readonly publication_status: string | null | undefined;
  readonly published_at: Date | string | null | undefined;
  readonly ranked_county_count: number | string | null | undefined;
  readonly row_count: number | string | null | undefined;
  readonly source_county_count: number | string | null | undefined;
}
