import { writeTextAtomic } from "./atomic-file-store";
import type { DuckDbRequiredExtension } from "./batch-artifact-layout.types";
import type { DuckDbBootstrapOptions } from "./duckdb-bootstrap.types";

export const DEFAULT_DUCKDB_BOOTSTRAP_EXTENSIONS: readonly DuckDbRequiredExtension[] = [
  "spatial",
  "httpfs",
  "postgres",
];

export function renderDuckDbBootstrapSql(options: DuckDbBootstrapOptions = {}): string {
  const includeInstallStatements = options.includeInstallStatements ?? true;
  const extensions = options.extensions ?? DEFAULT_DUCKDB_BOOTSTRAP_EXTENSIONS;
  const statements: string[] = [
    "-- Generated by the map batch-artifact bootstrap.",
    "-- Keep one writable DuckDB database per pipeline run.",
  ];

  for (const extension of extensions) {
    if (includeInstallStatements) {
      statements.push(`INSTALL ${extension};`);
    }
    statements.push(`LOAD ${extension};`);
  }

  return statements.join("\n");
}

export function writeDuckDbBootstrapSql(path: string, options: DuckDbBootstrapOptions = {}): void {
  writeTextAtomic(path, `${renderDuckDbBootstrapSql(options)}\n`);
}
